
service: aws-lambda-helloworld-api-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: deploy-lambda
  region: eu-central-1 

functions:
  hello:
    handler: handler.hello
    events:
      - http:
        method: get
        path: /helloworld
